linters-settings:
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - appendAssign
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/kylrth/freeblock
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 100
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    # see https://github.com/kunwardeep/paralleltest/issues/8
    - linters:
        - paralleltest
      text: "does not use range value in test Run"
    # no gomnd on test files
    - path: _test\.go
      linters:
        - gomnd

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
  # not enabled:
  # - cyclop
  # - errorlint
  # - exhaustivestruct
  # - forbidigo
  # - forcetypeassert
  # - gochecknoinits
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - gomnd
  # - noctx
  # - tagliatelle
  # - wrapcheck
  # - wsl
